#!/usr/bin/env ruby
# vim:set ft=ruby

require_relative './lib/path.rb'
require_relative './lib/migrator.rb'

migrator = Migrator.new(force: true)

# Create symlink from dot.xxx
Dir.glob('./dot\.*').each do |name|
  src = Path.from_cwd(name)
  dst = Path.from_home(name.gsub(%r{^\./dot}, ''))

  migrator.renew(src, dst)
end

# ~/.vim/rcs
migrator.renew(
  Path.from_cwd('dot.vim/rcs'),
  Path.from_home('.vim/rcs')
)

migrator.renew(
  Path.from_cwd('dot.vim/after'),
  Path.from_home('.vim/after')
)

migrator.renew(
  Path.from_cwd('dot.vim/snippets'),
  Path.from_home('.vim/snippets')
)

migrator.renew(
  Path.from_cwd('dot.vim/dein.toml'),
  Path.from_home('.vim/dein.toml')
)

migrator.renew(
  Path.from_cwd('dot.vim/dein_lazy.toml'),
  Path.from_home('.vim/dein_lazy.toml')
)

Dir.mkdir(File.expand_path('~/.git-templates')) unless Dir.exists?(File.expand_path('~/.git-templates'))
migrator.renew(
  Path.from_cwd('dot.git-templates/emoji_commit_template'),
  Path.from_home('.git-templates/emoji_commit_template')
)

# nvim
Dir.mkdir(File.expand_path('~/.config')) unless Dir.exist?(File.expand_path('~/.config'))
migrator.renew(
  Path.from_home('.vim'),
  Path.from_home('.config/nvim')
)

migrator.renew(
 Path.from_home('.vimrc'),
 Path.from_home('.config/nvim/init.vim')
)
