[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim")'
on_event = 'BufRead'
hook_post_update = 'TSUpdate'
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = 'maintained',
  ignore_install = { 'haskell', 'swift', 'phpdoc' },
  highlight = {
    enable = true,
    disable = {},
  },
  indent = {
    enable = true,
    disable = {'python'},
  },
  ensure_installed = 'all',
}
EOF
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

[[plugins]]
repo = 'ncm2/float-preview.nvim'
if = '''has('nvim')'''

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = ['plantuml']

#[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
hook_post_source = '''
  " enable auto format when write (detaul)
  let g:goimports = 1
  " gofmt -s
  let g:goimports_simplify = 1
  let g:goimports_cmd = "gci"
'''

########################################
# all of dependencies from here are used only for vim syntax highlighing
[[plugins]]
repo = 'vim-ruby/vim-ruby'
if = 'has("vim")'
on_ft = ['ruby', 'rake']

[[plugins]]
repo = 'keith/rspec.vim'
if = 'has("vim")'
on_ft = ['ruby']

[[plugins]]
repo = 'slim-template/vim-slim'
if = 'has("vim")'
on_ft = ['slim']

[[plugins]]
repo = 'groenewege/vim-less'
if = 'has("vim")'
on_ft = ['less']

[[plugins]]
repo = 'wavded/vim-stylus'
if = 'has("vim")'
on_ft = ['styl']

[[plugins]]
repo = 'lumiliet/vim-twig'
if = 'has("vim")'
on_ft = ['php']

[[plugins]]
repo = 'elixir-lang/vim-elixir'
if = 'has("vim")'
on_ft = ['exs']

[[plugins]]
repo = 'hashivim/vim-terraform'
if = 'has("vim")'
on_ft = ['terraform']

[[plugins]]
repo = 'sealemar/vtl'
if = 'has("vim")'
on_ft = ['vm']

[[plugins]]
repo = 'toyamarinyon/vim-swift'
if = ''' has('mac') && has('vim') '''
on_ft = ['swift']

[[plugins]]
repo = 'posva/vim-vue'
if = 'has("vim")'
on_ft = ['vue']

[[plugins]]
repo = 'leafgarland/typescript-vim'
if = 'has("vim")'
on_ft = ['typescript']

[[plugins]]
repo = 'cespare/vim-toml'
rev = 'main'
if = 'has("vim")'
on_ft = ['toml']

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
if = 'has("vim")'
on_ft = ['Dockerfile', 'docker-compose']
