[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'chemzqm/denite-git'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = ['javascript']
depends = ['deoplete']

#[[plugins]]
#repo = 'deoplete-plugins/deoplete-go'
#on_ft = ['go']
#depends = ['deoplete']

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

# [[plugins]]
# repo = 'tpope/vim-rails'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  let g:dein#plugin.build = 'make'
'''

[[plugins]]
repo = 'tpope/vim-endwise.git'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'rhysd/vim-lsp-ale'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
if = '''has('nvim')'''

[[plugins]]
repo = 'prabirshrestha/async.vim'
if = '''has('vim')'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'sbdchd/neoformat'
