[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

# [[plugins]]
# repo = 'tpope/vim-rails'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  let g:dein#plugin.build = 'make'
'''

[[plugins]]
repo = 'tpope/vim-endwise.git'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'rhysd/vim-lsp-ale'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
if = '''has('nvim')'''

[[plugins]]
repo = 'prabirshrestha/async.vim'
if = '''has('vim')'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'sbdchd/neoformat'
