[[plugins]]
repo = 'Shougo/unite.vim'
if   = '''has('vim')'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = '''has('nvim')'''
hook_add = '''
  nnoremap [denite] <Nop>
  nmap ' [denite]

  nnoremap <silent> [denite]b :<C-u>Denite buffer<CR>
  nnoremap <silent> [denite]f :<C-u>Denite file_rec<CR>
  nnoremap <silent> [denite]d :<C-u>Denite directory_rec<CR>
  nnoremap <silent> [denite]g :<C-u>Denite grep<CR>
  nnoremap <silent> [denite]r :<C-u>Denite -resume<CR>

  nnoremap <silent> [denite]p :<C-u>Denite -resume -immediately -select=-1<CR>
  nnoremap <silent> [denite]n :<C-u>Denite -resume -immediately -select=+1<CR>

'''
hook_post_source = '''
  call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', [])
  call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
'''

[[plugins]]
repo = 'Shougo/neocomplete'
if   = '''has('vim')'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if   = '''has('nvim')'''
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_ignore_case = 1
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#auto_complete_deplay = 10
  let g:deoplete#delimiters = ['/', '.']
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
    \ neosnippet#expandable_or_jumpable() ?
    \   "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
if = '''has('nvim')'''

[[plugins]]
repo = 'zchee/deoplete-go'
if = '''has('nvim')'''
on_ft = ['go']
depends = ['deoplete']

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  if has('nvim')
    imap <C-k> <Plug>(neosnippet_expand_or_jump)
    smap <C-k> <Plug>(neosnippet_expand_or_jump)
    xmap <C-k> <Plug>(neosnippet_expand_target)
    if has('conceal')
      set conceallevel=2 concealcursor=niv
    endif
  endif
'''
on_i = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  let g:dein#plugin.build = 'make'
'''

[[plugins]]
repo = 'tpope/vim-endwise.git'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
